version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - gateway-service
      - user-service

  gateway-service:
    image: gateway-service
    build:
      context: ./gateway-service/
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://yourusername:yourpassword@postgres:5432/yourdatabase
      NATS_URL: nats://nats-streaming:4222
    networks:
      - gateway-service
    depends_on:
      - postgres
      - nats-streaming
    ports:
      - "3000:3000"

  user-service:
    image: user-service
    build:
      context: ./user-service/
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://yourusername:yourpassword@postgres:5432/yourdatabase
      NATS_URL: nats://nats-streaming:4222
    networks:
      - user-service
    depends_on:
      - postgres
      - nats-streaming

networks:
  gateway-service:
    driver: bridge
  user-service:
    driver: bridge

volumes:
  postgres_data: